export { default as IAdmin } from './Admin.interface';
export { default as IAmount } from './Amount.interface';
export { default as INft } from './Nft.interface';
export { default as ISale } from './Sale.interface';
export { default as IStake } from './Stake.interface';
export { default as IStakeValue } from './StakeValue.interface';
export { default as ITransaction } from './Transaction.interface';
export { default as IUser } from './User.interface';
export { default as IManagement } from './Management.interface';
